### ISSUE TITLE
Expert - Cymru - Cache check by BGP or specific network mask

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#120]
https://github.com/certtools/intelmq/blob/master/intelmq/bots/experts/cymru/cymru.py#L7

is not right to do with /24, we need to use the BGP_prefix

**Comment by Phantasus** [comment]
Hi :-)

what is the state of this issue? Can it be closed? I mean it's open since a year
and supposed to be in release 1. Shouldn't all release 1 issues be closed by now,
as the devteam is bringing up a release 3 at the moment?

If not, I could try to help closing those issues as they have at the moment
reached an amount which is really confusing.

**Comment by wagner-certat** [comment]
Could you please explain in more detail what needs to be done?

**Comment by wagner-certat** [comment]
unclear what needs to be done here, no feedback
