### ISSUE TITLE
TCP collector tests: unused code

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1389]
According to the coverage report the code in `_delayed_start` and `chunked_process_replacement` is never executed. Maybe the code is no longer necessary or there is a bug in the test.

A coverage report can be seen here e.g.: https://codecov.io/gh/certtools/intelmq/src/master/intelmq/tests/bots/collectors/tcp/test_collector.py (and also locally)

**Comment by e3rd** [comment]
It was hard as crazy, writing the tests the right way took me at least about 10× more time than writing the actual bot.
If you put a `print` statement in there, you'd see both functions are used. But don't do that since simple `print` influences the test results. Crazy, eh? There's a lot of multiprocessing in there so I'm not surprised Code coverage is wrong about that. Is there a way to mute Code coverage?

![image](https://user-images.githubusercontent.com/6942231/55023302-c7908180-4ffc-11e9-94e6-c5efd7ba84f4.png)

![image](https://user-images.githubusercontent.com/6942231/55023324-d5460700-4ffc-11e9-90f3-7ced95cca250.png)
