### ISSUE TITLE
Abuse.ch parser error for ipblocklist.csv

### ISSUE THREAD

**Issue by kalyparker** [certtools/intelmq#1415]
Hi all,
I'm switching to the new feodo list from abuse.ch
https://feodotracker.abuse.ch/downloads/ipblocklist.csv

The actual bot miss the new field which is very interesting called "LastOnline".
This information can be usefull for adding the status, but I wish to keep this information.
I propose to add the LastOnline date in 'event_description.text'. 
What do you think?

Additionally, there is a mistake in the get of header, I can manage it in the same time.
I'll already did the modification on my side.

**Comment by wagner-certat** [comment]
Thanks. There was also a disussion in #1400 about that but we were unsure how to handle that correctly. I got the confirmation from abuse.ch that there's no time information, but it is UTC, so I now appended 'T00:00+00' to this field to save it in `extra.last_online` and use if as `time.source` if available. The fix is in the maintenance and develop branches and part of the next releases.

> Additionally, there is a mistake in the get of header, I can manage it in the same time.

I am not sure if I understand.

**Comment by kalyparker** [comment]
For the bot AbusechIPParserBot, 3 feeds are handled.
'https://feodotracker.abuse.ch/downloads/ipblocklist.csv'
'https://zeustracker.abuse.ch/blocklist.php?download=ipblocklist'
'https://zeustracker.abuse.ch/blocklist.php?download=badips'

For zeustracker the header of the feed are the same.
For feodo, the header is different and you need to change this line.

fields = comments[-1].split(',')
to
fields = comments[-2].split(',')

But doing that break the other feed.
So I add a parameter call position and change the line as it:
fields = comments[-FEEDS[feed]['position']].split(',')

**Comment by wagner-certat** [comment]
I've split this bug into #1417 , closing here for the ipblocklist.csv support
