### ISSUE TITLE
API for IntelMQ

### ISSUE THREAD

**Issue by Teebor-Choka** [certtools/intelmq#1424]
# Feature request: API for the MQ

`IntelMQ` is tightly coupled with existing utilities and tools (e.g. `CLI`, `IntelMQ manager` ...).  that would benefit from a separate API for the entire `MQ`.

These are difficult to do (correctly, no hacks) without a proper API to MQ:
- use a single CLI to provision MQ distributed over multiple machines (complicated horizontal scaling)
- separate `IntelMQ manager` from the machine running `IntelMQ` (complicated role separation, e.g. for microservice system architecture)
- write simple automatization for individual bot provisioning (e.g. Ansible)
- create automatization around bot stats, bot monitoring (other than log parsing), automatic bot scaling and management
- create automatization and MQ status (other than extracting queue information directly from redis)
- write custom tools/utilities for `IntelMQ` and/or direct integration into different external systems (e.g. SIEMs...)

Further benefits of the API:
- isolates the MQ from the rest of the utilities -> easier tool development (e.g. generating CLI using command mapping into API format,...)
- generalizes architecture simplifying future changes

Downsides:
- lots of work

**Comment by wagner-certat** [comment]
> Downsides:
> 
>     * lots of work

But it needs to be done. So let's collect some aims and use cases to then generate the requirements from them.

@certtools/intelmq-contributors what do you expect from a intelmq api?

For reference: the n6 api: https://github.com/CERT-Polska/n6/tree/master/N6RestApi

**Comment by Teebor-Choka** [comment]
To kick-off a more concrete design for the API:
- versioning - to allow separate development pace for the IntelMQ core and other utilities
- filtering operations on the content - reduce the amount of paths the interface can take by forcing the logic on API call producer
- in the first release it should achieve parity with the official utility requirements - specifically the `intelmqctl` and `IntelMQ manager` (please feel free to add more detail about each utility's requirements as my knowledge may be incomplete).

Assuming some sort of controller where the API is located, in order to facilitate the `intelmqctl` functionality it should at least be able to:

1. `configure` (bot harmonization.conf file can serve as a validation template)
   - `\bot` runtime parameters for each bot - direct inlay
   - `\pipeline` configuration for each bot - direct inlay

2. `manage`
   - `/bot` (start, stop...)
     - the entire botnet is a special case of globbing the name with `*`
     - groups based on attributes: `type: "<group_name>""

e.g. in a REST format this could look like:
```json
GET intelmq/manage/bot
{
  "version": 1.0,
  "action": "start",
  "filter": {
    "match_all" : {
      "type": "parser",
      "name": "shadowserver*"
    }
} 
```

For the IntelMQ manager these are important:

3. `show`
   - show current configuration and pipelines set up (can be limited to bots/groups similarly, using filters)
    - show bot metadata (queue status, bot status...)

For 3 to be efficient and isolated, a periodic automatic telemetry channel should be set up for each bot towards the controller, apart from the configuration channel from controller to the bot

Any other ideas?

**Comment by aaronkaplan** [comment]
Totally agreed. I referenced this in our 3.0 Architecture document. Thanks!

**Comment by bernhardreiter** [comment]
Note that please do not do a "RESTful" API, because it would mean that clients are not allowed to know about the possibilities of the return data (*). Also this API will not profit from the caching of idempotent calls, as it will not be high scaling but just for monitoring, configuration and control.

Call it a "HTTP based micro-service" API seems more sensible.

(*) The HATEOAS principle of RESTful interfaces does not allow clients to "know" much about the structure of the server application. This makes creating an SPA which a good usability a lot harder,
as a good user experience means that each element is places in a way that users understand the application.

**Comment by Teebor-Choka** [comment]
@bernhardreiter Could you elaborate on a more desired approach to designing a sensible 'HTTP based micro-service' API for IntelMQ?

**Comment by bernhardreiter** [comment]
@Teebor-Choka a desireable approach for the API for IntelMQ from my point of view is to consider the use cases for the interface and start small and simple. (As opposed to create powerful general abstractions early.) In general it makes sense to adopt a term for this interface that allows creating a good one for those use cases, my suggestion is `HTTP based micro-service' to make clear that CRUD or HATEOAS is not necessarily desired or required. Otherwise design as before, e.g. use JSON like before and HTTP protocol terms.

**Comment by aaronkaplan** [comment]
covered in the intelmq 3.0 architecture

**Comment by wagner-certat** [comment]
With IntelMQ 2.3.0 we have an API (https://github.com/certtools/intelmq-api https://intelmq.readthedocs.io/en/maintenance/user/intelmq-api.html) thanks to SUNET, Intevation and @schacht-certat.

As this issue is a collection of various ideas, suggestions and wishes, I suggest to close here and create new individual issues in the API repository for the remaining feature requests.
