### ISSUE TITLE
asn_lookup update script FTP vs HTTP

### ISSUE THREAD

**Issue by wagner-certat** [certtools/intelmq#1535]
The current asn_lookup / pyasn update script uses FTP to fetch the database from archive.routeviews.org, but we only used `http(s)_proxy` yet. So this won't work in some environments (including @certat's). So fixing https://github.com/hadiasghari/pyasn/issues/62 would still be nice, or alternatively https://github.com/hadiasghari/pyasn/issues/64

**Comment by gethvi** [comment]
Given the pyasn package is not currently maintained, a completely different option is to use GeoLite2 ASN and have maxmind_asn expert bot. However I can not say which one of the data sources is better in terms of quality.

Pros:
* reliable source and maintained geoip package
* one less dependency (because geoip package is already being used by other bot)

Cons:
* new bot needs to be implemented (but we already have almost the same code)

**Comment by wagner-certat** [comment]
Are you sure that the GeoLite2 database has a good enough ASN-IP address mapping?

With pyasn you can use any BGP routing table which makes you very independent from (one) external data source(s).

**Comment by wagner-certat** [comment]
fixed by #1524
