### ISSUE TITLE
Extra - Automatic unit testing

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#159]
intelmq so far completely lacks unit testing features. It would be very important to have unit testing in place - especially since the project is growing. 

There are a couple of mechanisms in Python to do unit testing - for example: https://docs.python.org/2/library/unittest.html 

For unit-testing individual  bots, I propose having a special "testing" mode where a well defined pipeline data comes into the bot and goes out of the bot. Then it is compared against expected output.

Comments welcome :)

**Comment by chorsley** [comment]
Having just worked through a project using unit / integration testing, I've found the following very useful: 

* For enhanced test discovery / utility functions: http://nose.readthedocs.org/en/latest/index.html
* For mocking return values and exceptions: http://www.voidspace.org.uk/python/mock/mock.html
* For date manipulation: https://github.com/spulec/freezegun

Tox also seems to be getting a lot of attention of late: http://tox.readthedocs.org/en/latest/

**Comment by aaronkaplan** [comment]
Thanks Chris! Will take a look

**Comment by SYNchroACK** [comment]
https://github.com/certtools/intelmq-unit-test

Any feedback?

**Comment by Phantasus** [comment]
I add here the links to my testing proposals: #236 (better TestCase) and #229, so that everything is linked together. My proposal uses python stdlib unittest, which has the following advantages:

1. No custom test-runner must be implemented (the general advantage of using a framework or library)
2. It ships with python (as also doctest does)
3. It uses a unittesting concept which is widely supported (so much supported that this kind of unittests are also called "xunit" (see https://en.wikipedia.org/wiki/XUnit). So in the worst circumstances the project tests can be written by Java-coders who happen to play with python (*hint* JUnit *hint*).

**Comment by sebix** [comment]
Fixed by #282 when merged.

**Comment by Phantasus** [comment]
Interesting what is going on there? Does anybody still know what is current?

**Comment by sebix** [comment]
@Phantasus master is now the current dev branch, if you mean that. But there are many upcoming features and fixes in my fork.
