### ISSUE TITLE
load-data-problem

### ISSUE THREAD

**Issue by oencarnacion** [certtools/intelmq#2118]
Bot has found a problem.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/intelmq/lib/bot.py", line 272, in start
    self.process()
  File "/usr/lib/python3/dist-packages/intelmq/lib/bot.py", line 1005, in process
    for line in self.parse(report):
  File "/usr/lib/python3/dist-packages/intelmq/bots/parsers/shadowserver/parser.py", line 80, in parse
    raise ValueError('Could not get a config for {!r}, check the documentation.'
ValueError: Could not get a config for 'special', check the documentation.

**Comment by waldbauer-certat** [comment]
Hey @oencarnacion 

It seems that you havent configured the shadowserver parser yet. To configure it correctly, you can checkout the [documentation](https://intelmq.readthedocs.io/en/maintenance/user/bots.html#shadowserver).

Cheers,
Sebastian

**Comment by oencarnacion** [comment]
just restart the redis and it works as normal

**Comment by ghost** [comment]
Although this issue is closed already I believe the circumstances were a bit different. It looks like you have ingested one of Shadowservers "special" reports into the shadowserver parser. As described in the shadowserver parser bot's documentation linked above by my colleague, the bot has two possibilities to detect how to parse a report: either the parameter "feedname" is set to one of the allowed values, or the feed is detected from the filename. You haven't set "feedname" and the autodetect mechanism jumped in, detecting the feed name "special", extracted from the filename. However, we have not implemented a mapping for this feed, as it is special, as the name says :)
