### ISSUE TITLE
Bots to improve

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#226]
* sanitizer
* postgresql
* hpfeeds

remove the following bots because they will be included in a specific pull req with a lot of bots:
* cert-eu
* shadowserver

**Comment by Th4nat0s** [comment]
filterbot should also understand AS and cidr (everybody is not a country cert :).
I could handle it since I need it :) .. 

I think about a property "match" which could be a csv list with 2 letter country, ASxxxx, Ipv4 or Ipv6 cidr. and a property "usage" which could be "drop" or "keep" to invert selection.

So With the same filter on may remove "things" or "select things".

Is it ok ?

**Comment by SYNchroACK** [comment]
@Th4nat0s check filter expert bot please.

**Comment by Th4nat0s** [comment]
Sorry i didn't understand what you mean, I see no filter beside the country code one in the branch v1 in the expert folder.

**Comment by SYNchroACK** [comment]
https://github.com/certtools/intelmq/tree/v1.0-beta/intelmq/bots/experts/filter

**Comment by SYNchroACK** [comment]
moved to https://github.com/certtools/intelmq/issues/93
