### ISSUE TITLE
IntelMQ deb build on Debian 12 fails because of wrong installation path

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#2384]
The build of the Debian package on Debian 12 fails, as the executables and libraries are not installed to usr/bin but rather to usr/local/bin
I see no obvious reason in the rules file, why pybuild uses this non-standard directory now.

**Comment by sebix** [comment]
last bit of the log
```
[  439s] # remove program not needed for packages
[  439s] rm debian/intelmq/usr/bin/intelmqsetup
[  439s] /bin/rm: cannot remove 'debian/intelmq/usr/bin/intelmqsetup': No such file or directory
```
https://build.opensuse.org/package/live_build_log/home:sebix:intelmq:unstable/intelmq/Debian_12/x86_64

**Comment by kamil-certat** [comment]
There is more worrying things in the log, like:

> [  124s] /usr/lib/python3/dist-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'intelmq.bots.collectors.alienvault_otx' as data is deprecated, please list it in `packages`.
[  124s]     !!
[  124s] 
[  124s] 
[  124s]     ############################
[  124s]     # Package would be ignored #
[  124s]     ############################
[  124s]     Python recognizes 'intelmq.bots.collectors.alienvault_otx' as an importable package,
[  124s]     but it is not listed in the `packages` configuration of setuptools.
[  124s] 
[  124s]     'intelmq.bots.collectors.alienvault_otx' has been automatically added to the distribution only
[  124s]     because it may contain data files, but this behavior is likely to change
[  124s]     in future versions of setuptools (and therefore is considered deprecated).
[  124s] 
[  124s]     Please make sure that 'intelmq.bots.collectors.alienvault_otx' is included as a package by using
[  124s]     the `packages` configuration field or the proper discovery methods
[  124s]     (for example by using `find_namespace_packages(...)`/`find_namespace:`
[  124s]     instead of `find_packages(...)`/`find:`).
[  124s] 
[  124s]     You can read more about "package discovery" and "data files" on setuptools
[  124s]     documentation page.
[  124s] 
[  124s] 
[  124s] !!

Anyway, maybe we can use `pybuild --install` instead of `python3 setup.py install`?

https://github.com/certtools/intelmq/blob/9750181a67b1a035f4269550541d2ca2d3137256/debian/rules#L39

This is the only place I see now something that may affect the way we install packages, although it looks it shouldn't.

(https://salsa.debian.org/python-team/tools/dh-python)

**Comment by sebix** [comment]
I replaced `python3 setup.py install` in the `override_dh_auto_install` section of `debian/rules` and it seems to work, at least it builds correctly:
https://build.opensuse.org/package/live_build_log/home:sebix:intelmq:unstable/intelmq/Debian_12/x86_64
I only tried it on OBS and haven't commited anything in the GitHub repository

**Comment by kamil-certat** [comment]
Nice to see that, I hope it's the solution

**Comment by kamil-certat** [comment]
@sebix Have you managed to fix the problem? We had some releases since then, is it still a valid issue?

**Comment by sebix** [comment]
@kamil-certat see #2391
