### ISSUE TITLE
Transversal bug - check if contains raw

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#264]
The following line which is present in all bots doesnt make sense. Remove the check.
https://github.com/certtools/intelmq/blob/v1.0-final/intelmq/bots/parsers/arbor/parser.py#L13

**Comment by SYNchroACK** [comment]
In the situation mentioned before, the message will be acknowledge but the process will continuing... which doesn't make any sense. @sebix , make sense for you what I'm saying?

**Comment by sebix** [comment]
This line has first been introduced by you on Sun Jun 29 2014 in commit 6988fe2.
View the diff:

    git diff 6988fe2cc1a2fb6d71273bea30a73c910b74f84e~ 6988fe2cc1a2fb6d71273bea30a73c910b74f84e

Commit found with with `git log --all --source --reverse -S 'self.acknowledge_message()'`.

In the diff you can see, that `self.pipeline.acknowledge()` has been replaced by `self.acknowledge_message()` which calls the other function (and nothing else).

The `acknowledge` rpops the last message from the internal queue, as the `acknowledge` function moves the message from source queue to internal queue. This won't work with more bots working in parallel, but currently this line is necessary otherwise the parser will get the same message again in the next call of `receive`. As far as I understand the code, haven' tested it.

**Comment by sebix** [comment]
Is this issue resolved? Now bots do not further processing (return), when there's no raw field.

**Comment by SYNchroACK** [comment]
yes. ty
