### ISSUE TITLE
"time.source" field is not filled up with some bots

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#388]
We have a problem with some bots which don't provide a ```time.source``` field. At the recipient (ISP, network operator ) side, there is no way someone can find such an IP address in large log files without a timestamp (and time zone)!

Hence we have a few options:
  1. we provide time info via ```time.observation``` (i.e. when we found the event in some blocklist etc) **and** provide a way to verify our claim (for example: "is an open recursive DNS server") - something that people can check themselves, or...
  2. we ignore these events intentionally since they create more work for the recipient without adding any value.

So, I think we need to go through each bot/parser and see which case applies and act accordingly.

**Comment by robcza** [comment]
I can not agree with this proposal, I'll try to explain my reason. I see these three types of events:

1. "seen first" stated and used as time.source, however no information regarding "seen last"
  - it is obvious when it started, you have to guess, when it ends
2. "seen first" and "seen last" both published by the feed, "seen first" used as time.source
  - start and end both obvious
3. no information regarding when was the event recorded - mostly assuming it was during the last update of the report
  - start/end very blurry, could be possibly refined based on report update period

Filling time.source with time.observation in case the original events do not include the timestamp would result in a situation, where you are not able to decide whether time.sources is the original value or it was just added by IntelMQ as a guess. That could be very confusing on the output.

On the other hand, I understand the need for a single and primary timestamp value included in every value. I would go for the logic proposed by @aaronkaplan however instead of using time.source I'd used time.seenfirst or something similar

**Comment by aaronkaplan** [comment]
@robcza : I agree with you! Actually, after some internal discussions, I had to correct my original issue report. It seems the situation is a bit more complex (as you also noted as well).

We'll think about it some more...

**Comment by aaronkaplan** [comment]
@robcza : do you know if we can add a timestamp field to the turris feed? That's still needed. Then we can set ```time.source``` to the feeds' time stamp field.

**Comment by sebix** [comment]
For the record, these feeds (parsers) do not provide a time.source: Turris, Blocklist.de, abuse.ch, fraunhofer dga

Actually, exactly these have been tested, so the list is far from complete.

**Comment by sebix** [comment]
The complete list of parsers, not writing `time.source`:

* abuse.ch (both IP and domains)
* alienvault (not otx, the normal one)
* blocklist.de
* ci army

Can't test:
* arbor (403 access denied)

To be continued...

**Comment by aaronkaplan** [comment]
let's still get arbor fixed. I'll help you with it.

**Comment by aaronkaplan** [comment]
@sebix lets' do that...

**Comment by aaronkaplan** [comment]
we will never have only feeds which always contain a "time.source" field.
We therefore need to leave the decision up to the user if he/she wants to use these types of feeds.
