### ISSUE TITLE
collectors rate_limit vs. cron

### ISSUE THREAD

**Issue by robcza** [certtools/intelmq#464]
Recently encountered a situation, where I would prefer to run the collector in a fixed schedule instead of regular cycles starting in the moment the bot is started.
This could be useful for feeds, that publish their updates in fixed time (e.g. midnight) and intelmq could collect that feed just in time and just once.

**Comment by aaronkaplan** [comment]
agreed. Should work out easily as long as the destination queue and source queues don't fill up. Why not? However, what does this change in the basic bot class?

**Comment by sykaeh** [comment]
Any new developments on this? I would need to be able to schedule collectors as well.

**Comment by sebix** [comment]
The only feature needed here is to exit bots after a successful run, or - depending on the use case - one run without results (e.g. tickets).

**Comment by sebix** [comment]
The only feature needed here is a "oneshot" (called like that in systemd and supervisord too). E.g.:

    intelmqctl start --oneshot http-collector

**Comment by ondj** [comment]
@sebix Yes, but also command `intelmqctl start` have to not starts oneshot bot. Maybe use for this `enabled` param when #815 will be resolved?

**Comment by sebix** [comment]
Sure

**Comment by sebix** [comment]
Should the rate_limit be completely removed or just not the default.

Also, Would you like to have a more generic approach, e.g. giving the number of total allowed iterations?

**Comment by SYNchroACK** [comment]
@sebix @aaronkaplan @robcza Do you guys agree?

**My opinion:**

1. I agree with the need for this feature.
2. I think `rate_limit` should never be remove.
3. I disagree the use of `systemd` and `supervisord`. IntelMQ should be independent from operating system in core functionalities.
4. `rate_limit` should continue as default
5. Yes, generic approach.

**Proposal:**
* If a bot has defined the field `schedule_time` in the configuration, the `rate_limit` should be ignored and the bot will process (run the `process()` method) on the defined second/minute/hour...
**Note:** the configuration field name is just an example, my main concern is the way to implement this feature.

@sebix @aaronkaplan feedback?

**Comment by wagner-certat** [comment]
> I think rate_limit should never be remove.

Then we need to do a very bad reimplementation of cron :/

> I disagree the use of systemd and supervisord. IntelMQ should be independent from operating system in core functionalities.

Again, we are reinventing the wheel. The user has the choice which one to use. The intelmqctl itself is the worst choice of all. It's error-prone, can't be monitored etc.

In short: No, I disagree.

**Comment by SYNchroACK** [comment]
* [Run Modes](#run-modes)
    * [Configuration](#configuration)
    * [Description](#description)
    * [Examples](#examples)
    * [Bot Examples](#bot-examples-run-modes)
    * [Requirements](#requirements)
  * [Rate Limits](#rate-limits)
    * [Configuration](#confiiguration)
  * [Feedback](#feedback)

# Proposal

The following information is just a proposal to re-structure the running mode of bots, according to multiple questions and issues related to the need of different approaches to fetch feeds and other possible scenarios that you may think of.

**Note:** the names, values and other terms are merely names that I used to explain my proposal. They don't need to be called like that in the code or in the documentation, although, is extremely important to define clear and intuitive names in the implementation phase.

## Run Modes

Each bot has their own purposes, therefore there is a need for configuration that would allow diferent **run modes**. Looking at the current IntelMQ implementation and as far I'm aware, there are 2 run modes required as the following section shows:

### Configuration

| Run Mode  | Run Mode Config `parameter` | Extra Config  | Extra Config `parameter`  | Implement on Milestone |
|---|---|---|---|---|
| Scheduled | `"run_mode: "scheduled"` | Crontab Time String Syntax | `"crontab": "0 0,12 1 */2 *"` | v1.0 |
| Stream | `"run_mode: "stream"` | None | None | v1.0 |

### Description

**Run Mode: Scheduled** - bots that need to run on specific time (hour, day, etc), requires to be configured as `scheduled` with an extra parameter using the well-known crontab syntax.

**Run Mode: Stream** - bots that need to run indefinitely in time, requires to be configured as `stream`. 

### Examples
Scheduled `runtime.conf` configuration example:
```
{
  ...
  "run_mode": "scheduled",
  "crontab": "0 0,12 1 */2 *",
  ...
}
```

Stream `runtime.conf` configuration example:
```
{
  ...
  "run_mode": "stream",
  ...
}
```

### Bot Examples / Run Modes

| Bot / Type | Run Mode |
|---|---|
| Mail / Collector | Scheduled |
| HTTP / Collector | Scheduled |
| File / Output | Scheduled |
| HTTP-Stream / Collector | Stream |
| Abusech / Parser | Stream |
| Deduplicator / Expert | Stream |
| CymruWhois / Expert | Stream |

### Requirements

I think there are two requirements for this implementation, however, I would like to have your feedback on this @wagner-certat because of the `systemd` implementation. We need to evaluate if this proposal will be compliant with the possible `systemd` implementation. The requirements are the following:

* both run modes MUST keep using the `rate_limit` parameter.
* `intelmqctl` will be responsible to use the **python-crontab** library to write into crontab system (if run_mode is scheduled) or execute the bot (if run_mode is stream).



## Rate Limits

Rate limits are independent from run a bot in `stream` or `scheduled` mode. The only improvement that I can see for rate_limits is the following (mind the milestones):

The implementation proposed for the `rate_limit` parameter would use a custom syntax depending of the purpose (seconds per event (`endswith('s')`) or events per second (`endswith('e')`). As far as I can see, the implementation of the **events per seconds** feature will require some additional efforts, I suggest to postpone this one to v1.1 milestone and keep with the current **seconds per event** implementation.

### Confiiguration

| Run Mode Specification  | Run Mode Specification Config `parameter`  | Implement on Milestone |
|---|---|---|
| Rate Limit (Number of Seconds per event) | `"run_mode_specification": "1s"` | v1.0 |
| Rate Limit (Number of Events per second)  | `"run_mode_specification": "4e"` | v1.1 |


# Feedback

@aaronkaplan @wagner-certat @dmth @sykaeh @ondj @robcza  give some feedback if you have chance. Thank you :)

**Comment by wagner-certat** [comment]
Please keep the number of breaking changes for 1.0 low, we want to the reach this milestone soon.

Why do you want to keep rate_limit for scheduled bots at all? Do you see any use case?

Reloading bots: Only send SIGHUP, don't silently enable things. Let's keep it consistent please.

Also note that systemd can be replaced by other init systems such as supervisord.
