### ISSUE TITLE
[8] performance: improve speed of deduplicator

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#613]
try to load all shadowserver data of the last years into intelmq -> will detect that the bottleneck (without any external network lookups) actually is the deduplicator.

**Comment by bernhard-herzog** [comment]
I've investigated this a bit. Naively one might expect the time to be spent in the actual hashing or in managing the cache, because that's what is different from other expert bots. It isn't. Turns out, it's mostly spent in the copy module (see more detailed analysis below)! I think the best solution is probably to not copy the event at all and change the implementation of the event object's hash method so that it

 1. can be called directly without going through the `hash` built-in (see #658)

 2. takes an optional parameter for the fields that should be ignored when computing the hash

I've implemented some of this for testing purposes. I'm going to prepare a pull request for this.

### More detailed analysis of the speed problems

The profile output says:

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000  123.676  123.676 {built-in method exec}
        1    0.000    0.000  123.676  123.676 <string>:1(<module>)
        1    0.078    0.078  123.676  123.676 bot.py:95(start)
     6651    0.284    0.000  123.556    0.019 expert.py:21(process)
   271238    2.570    0.000   73.983    0.000 message.py:105(add)
     6651    0.248    0.000   49.976    0.008 bot.py:275(receive_message)
     6650    0.121    0.000   49.824    0.007 copy.py:67(copy)
     6650    0.558    0.000   49.545    0.007 copy.py:272(_reconstruct)
   138944    0.471    0.000   48.992    0.000 message.py:102(__setitem__)
   271238    2.679    0.000   47.064    0.000 message.py:194(__is_valid_value)
[...]
     6650    0.038    0.000    4.441    0.001 {built-in method hash}
     6650    0.028    0.000    4.403    0.001 message.py:223(__hash__)
```

To get that output I've modified the deduplicator bot:

```diff
@@ -38,4 +52,6 @@ class DeduplicatorExpertBot(Bot):
 
 if __name__ == "__main__":
     bot = DeduplicatorExpertBot(sys.argv[1])
-    bot.start()
+    import cProfile
+    cProfile.run("bot.start()", "/tmp/deduplicator-stats")
+
```

Then I've added some feed data while the deduplicator was stopped so that a good number of events was in its input queue and I started the bot and stopped it again when the queue was empty. The resulting stats file can be processed in Python with

```python
>>> import pstats
>>> p = pstats.Stats("/tmp/deduplicator-stats")
>>> p.strip_dirs()
>>> p.sort_stats('cumulative').print_stats()
```

**Comment by aaronkaplan** [comment]
Excellent analysis! Thanks!

**Comment by bernhard-herzog** [comment]
I've created pull request #724 for the speed improvement. Processing rate almost doubles on my development system.
