### ISSUE TITLE
shadowserver parser does not always set classification fields

### ISSUE THREAD

**Issue by bernhard-herzog** [certtools/intelmq#645]
The shadowserver parser's config.py sets classification.identifier for most feeds but not for Botnet-Drone-Hadoop, Microsoft-Sinkhole, Sinkhole-HTTP-Drone, Ssl-Freak-Scan, Ssl-Scan. Similarly, it does not set classification.taxonomy for Ssl-Freak-Scan and Ssl-Scan.

**Comment by aaronkaplan** [comment]
**Re: Botnet-Drone-Hadoop**:

If you take a look at https://www.shadowserver.org/wiki/pmwiki.php/Services/Botnet-Drone-Hadoop, you will find a table of "types" (internal shadowserver names for certain infections).
That's what's probably the best to put into "classification.identifier" since the latter is really an internal "type" / "identifier" within an intelmq installation as well.
So, in order to solve this now, I will put a generic identifier into the shadowserver parser for Botnet-Drone-Hadoop and possibly the modify bot will have to set a more detailed identifier later.

**Comment by aaronkaplan** [comment]
should be fixed. Please re-open if you think otherwise.
