### ISSUE TITLE
[5] overwrite vs. override

### ISSUE THREAD

**Issue by aaronkaplan** [certtools/intelmq#720]
``` bash
% sudo grep override /opt/intelmq/etc/* | wc -l                                                                                                                              
21
% sudo grep overwrite /opt/intelmq/etc/* | wc -l                                                                                                                              
3

```

We should be consistent.

**Comment by bernhardreiter** [comment]
Looking into what would need to be done:

git log HEAD^1.. | grep 'comm\|Da'
commit 7d1408b538c3cbf7c8722c7611f7a22bd6769c2f
Date:   Mon Oct 17 10:01:42 2016 +0200

```
grep -ri override . -l
./debian/rules
./docs/User-Guide.md
./docs/Developers-Guide.md
./intelmq/bots/BOTS
./intelmq/bots/parsers/shadowserver/parser.py
./intelmq/bots/parsers/shadowserver/README.md
./intelmq/bots/experts/contact_db_lookup/expert.py
./intelmq/lib/bot.py
```

* rules is packaging, ok.
* User-Guide.md:  should be changed.
* Developers-Guide.md and bot.py: That is fine because object oriented "method overriding" is meant, see https://en.wikipedia.org/wiki/Method_overriding
* BOTS + shadowserver , that only shadowserver
* contact_db_lookup/expert.py: needs change

**Comment by bernhardreiter** [comment]
I've tried to fix this issue in https://github.com/Intevation/intelmq/tree/dev-better-code-01
but I got stuck over the definition of "feed.name" and "feedname" and the subsequent behaviour of
the "overwrite" parameter in the shadowserver parser.  However this is still an improvement.
