### ISSUE TITLE
DHO: Meaning of the field "feed.url"

### ISSUE THREAD

**Issue by dmth** [certtools/intelmq#749]
https://github.com/certtools/intelmq/pull/735 raised a discussion on the meaning of the field `feed.url`

We should talk about this, using this issue.

Currently at least two different interpretations are present
1. The field intends the URL to the feeds data
2. The field intends the URL to the feeds documentation

**Comment by sebix** [comment]
I only know of bots which use interpretation 1. For file, ftp, http, mail-url and rt collector it's always the resource to fetch.

Documentation was previously linked in the bot's description, now it's in [docs/Feeds.md](https://github.com/certtools/intelmq/blob/master/docs/Feeds.md).

**Comment by dmth** [comment]
My opinion is, that `Interpretation 2` is the way to go.
The URL to the data might contain a token to access it, or changes with each report.
Whilst, the URL to the documentation of the Feed seems to be more stable.

Maybe we should also discuss: Do we need this field at all?
Would a field `feed.provider.url, storing the feed-provider's website url, make more sense?
I'm not aware that this field is used apart for documentation reasons.

**Comment by SYNchroACK** [comment]
I don't remember the reason, in the beginning of the project, we added this field. In fact, as you @dmth raise, `Do we need this field at all?`. I really don't think so and +1 to remove it.

**Comment by aaronkaplan** [comment]
---
Mobile

> On 29 Dec 2016, at 10:06, SyNchroAcK <notifications@github.com> wrote:
> 
> I don't remember the reason, in the beginning of the project, we added this field. In fact, as you @dmth raise, Do we need this field at all?. I really don't think so and +1 to remove it.
> 

No actually I think it does make sense. 
Imagine a public blacklist. It is always great as a CERT to be able to point to the source and say "at this time your IP was on this URL (blacklist). 

It's a matter of giving as much proof as we can. 

I'd leave it

**Comment by aaronkaplan** [comment]
Adding to my previous comment: I agree with Sebix, interpretation 1 is better. 

But of course, a URL to the documentation of a feed is also quite important and we forgot to add that to the DHO. 



---
Mobile

**Comment by SYNchroACK** [comment]
Both interpretations makes sense but does not mean that every single event need an URL. From my perspective, the feed.name should provide a good name which can be used to traceback in the runtime.conf to the original Feed URL. But anyway, not a big deal for me to keep the field.

**Comment by sykaeh** [comment]
I think keeping `feed.url` with interpretation 1 is the way to go. For one, this is how it is already implemented in most parsers (if applicable) and when I first started working with IntelMQ this is the meaning that I intuitively understood under the field name. As Aaron said, it can be very useful to be able to point to the original source. While you can probably figure out the original feed URL from `runtime.conf` and the feed name, it is a lot easier to have it in the event itself (not to mention that if you change your `runtime.conf` it might not match later). I don't think having changing urls or access tokens is a reason not include it. If the URL changes, then there is even more reason to include it so that you have a reference to it later. If the URL includes an access token, it makes it easier for the CERT to quickly check the original source. Whether you share this information with other organizations is a completely different matter anyways. Also, if we remove the field we might introduce some breaking changes for certain setups. 

> Would a field `feed.provider.url, storing the feed-provider's website url, make more sense?

I would argue against introducing `feed.provider.url`. First, I don't think introducing another layer of nesting is worth it since it can lead to issues with hierarchical data and we would then need to change `feed.provider` to `feed.provider.name` to make it compatible. Second, I think a link to the documentation of the specific feed is far more useful than the provider itself. Usually it is not very difficult to find the provider's main website, but in some cases it's difficult to find the feed documentation or not clear exactly which feed this event came from (for example Shadowserver with a lot of feeds with similar names). So, if we are going to add a field for feed documentation I would make it `feed.documentation` with the URL to the documentation of the specific feed. Getting from the feed's documentation to the provider's main website is trivial in most cases.

**Comment by SYNchroACK** [comment]
Ok, @sykaeh good justification.

From my side, lets move on with the 1st approach.

@aaronkaplan are we in same page? :)

**Comment by dmth** [comment]
If 1) is the way to go, at least the Mail-Collector needs to be extended in order to add the url which was stripped from the E-Mail to the report.

**Comment by wagner-certat** [comment]
Ok, we agree on the meaning of `feed.url`. But do we want to have a `feed.documentation` too now?

**Comment by SYNchroACK** [comment]
> Ok, we agree on the meaning of feed.url. But do we want to have a feed.documentation too now?

I would go for it.
