### ISSUE TITLE
Parse x'd IP addresses to network

### ISSUE THREAD

**Issue by sebix** [certtools/intelmq#827]
convert `127.0.0.xxx` to cidr notation `127.0.0.0/24`

**Comment by dmth** [comment]
I'm afraid I don't understand what shall happen here...

- When should this happen?
- Do feeds axtually provide x'ed IP-Adresses, for what?
- What happens if this is a `source.ip`: is the core capable of handling CIDR notation instead of ips?

In addtion: I'm afraid one cannot deduce the size of the network from the information which is available here.  How do you get the Information that the network is a `/24` it might also be a `/28`?


```
Network:   192.168.0.0/24       11000000.10101000.00000000. 00000000
HostMin:   192.168.0.1          11000000.10101000.00000000. 00000001
HostMax:   192.168.0.254        11000000.10101000.00000000. 11111110
```
```
Network:   192.168.0.0/28       11000000.10101000.00000000.0000 0000
HostMin:   192.168.0.1          11000000.10101000.00000000.0000 0001
HostMax:   192.168.0.14         11000000.10101000.00000000.0000 1110
```

**Comment by wagner-certat** [comment]
I thought that n6 was doing this, but they do it the other way round :/ They send `xxx.xxx.1.1` which is pretty useless and can't be sanitized properly.

So I will close this again until we actually see this in the wild.

> What happens if this is a source.ip: is the core capable of handling CIDR notation instead of ips?

No, this can go into `*.network`.

> I'm afraid one cannot deduce the size of the network from the information which is available here.

Take the biggest range if unsure.
