### ISSUE TITLE
New Bot: IntelMQ CollectorBot

### ISSUE THREAD

**Issue by SYNchroACK** [certtools/intelmq#849]
Intelmq collector: basically a tcp collector, opening a local port.

related to the pull request #171 

check this [code](https://github.com/certtools/intelmq/pull/171/commits/d64673f96473143a88d5ee0a0279d7677ae782c0)

**Comment by dmth** [comment]
Uh. Nope. An IntelMQ - Collector is not just a Bot openeing a TCP port. This might only be the case if you are using a RedisMQ as a backend (and allow access to this queue for other parties i.e. via a vpn).

If you don't want other parties to have this access, a more elaborate solution is required. This might be a workaround via XMPP or something completely different.

**Comment by wagner-certat** [comment]
RabbitMQ (n6 and warden use it) has proven to be a very good messaging queuing system. Doing all the management and error handling in TCP could be a hilarious work, but that's opposing the KISS principile IMHO.

**Comment by SYNchroACK** [comment]
> RabbitMQ (n6 and warden use it) has proven to be a very good messaging queuing system. Doing all the management and error handling in TCP could be a hilarious work, but that's opposing the KISS principle IMHO.

fair enough

**Comment by wagner-certat** [comment]
See also https://gist.github.com/razuz/fc5b5c84666132bd8e68f0a6cd22a50f for a HTTP input

**Comment by e3rd** [comment]
Here is the first draft #1220 of the IntelMQ Collector. I've checked the bot is fully working, the tests will be working after we'll have handled some important questions.

* [ ] 1. Feed.name and feed.accuracy are the two only mandatory collector parameters, right? When connecting the two IntelMQ instances, the problem is, the original feed.name would be overwritten.
message from a feed → first IntelMQ sets feed.name as "example.feed" → tcp output → tcp input of the second IntelMQ need to set its own feed.name (e.g. "tcp-input")
* override this funcionality and let the feed.name = "example.feed" (implemented in the current PR), for the sake the second IntelMQ'll have a message with a feedname non-existing in the scope of the current runtime.conf 
* overwrite the feed.name and trash the original information
* overwrite the feed.name and store the original information to extra.feed.name (if that's free... but what about the usecase of sending to a third IntelMQ?)
* ...?

* [ ] 2. Since messages are coming from another IntelMQ, there is really no need of parser, am I right? However, a collector bot can't be directly connected to an expert bot, IntelMQ manager imposes it. How to solve this?
* we'll make a really dummy TCP parser bot :(
* we'll move the collector to the parser group and tolerate a collecting parser :(
* we'll allow a collector→expert pipeline
* ...?

* [ ] 3. Is separator parameter really needed? Why? Does somebody depends on having separator parameter? It seems to me that much cleaner idea would be to remove it from both output and collector bot and replace it by sending the message length via a standard struct object.
	https://stackoverflow.com/questions/17667903/python-socket-receive-large-amount-of-data

**Comment by wagner-certat** [comment]
> Here is the first draft #1220 of the IntelMQ Collector. I've checked the bot is fully working, the tests will be working after we'll have handled some important questions.

Great, thanks for your work!
> * [ ] 1. Feed.name and feed.accuracy are the two only mandatory collector parameters, right?
I think we can remove this and make them optional, only add them if they are given.
> When connecting the two IntelMQ instances, the problem is, the original feed.name would be overwritten.

That happens in the parser, see below. Currently, the json parser uses event.update, ie. the data in the event wins. The simplest solution would be to add a parameter `overwrite` to the parser to let the user decide. Both scenarios can be useful.
> * [ ] 2. Since messages are coming from another IntelMQ, there is really no need of parser, am I right? However, a collector bot can't be directly connected to an expert bot, IntelMQ manager imposes it. How to solve this?

But the data is some encoded/serialized and needs to be parsed. With JSON, in this case. So all in all it's this: TCP Output (serializing) -> TCP Collector -> JSON Parser (unserializing)
> * [ ] 3. Is separator parameter really needed? Why? Does somebody depends on having separator parameter? It seems to me that much cleaner idea would be to remove it from both output and collector bot and replace it by sending the message length via a standard struct object.

No opinion on that. Whatever makes sense.

**Comment by e3rd** [comment]
> 1. add a parameter overwrite 

Great idea! Ok

> 2.

I fear I don't know how to connect it with JSONParserBot. It does: `lines = [base64_decode(report['raw'])]`. When accepting a new TCP data from another IntelMQ, it's not base64 encoded.  
All the parsing the collector does is this line: `event = Event(Event.unserialize(utils.decode(event)))`.  
I may create a TCPParser bot that does this line...

I'm not very experienced in creating Collectors, help me further with your opinion please!

> 3. 

Ok!

**Comment by wagner-certat** [comment]
> > 2.
> 
> I fear I don't know how to connect it with JSONParserBot. It does: `lines = [base64_decode(report['raw'])]`. When accepting a new TCP data from another IntelMQ, it's not base64 encoded.  

`raw` is always base64-encoded (automatically) when the Collector adds data to it.

**Comment by e3rd** [comment]
Yeah, but the event has already been parsed from raw to other field in the first IntelMQ. Since raw comes from an IntelMQ and not from a clearly-defined source, we doesn't know what should be parsed anyway.  
However, I think I may do a blank dummy parser that just passes the message without doing anything.

By the way, should the name of the bot be IntelMQCollector OR TCPCollector? We have an TCPOutput that can be connected to whatever (so the name TCPOutput is logic) but this Collector can accept data only from another's IntelMQ TCPOutput so that the name should be IntelMQCollector, and not a TCPCollector, right?

**Comment by e3rd** [comment]
Please ignore the previous message, **don't reply**, the JSON Parser is a good solution, I'm working on it, I just need to finish tests and we're done.

**Comment by wagner-certat** [comment]
done
